import { useCallback, useEffect, useRef, useState } from "react";
import { Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { generateLesson } from "@/lib/generate-lesson.functions";
import { LessonViewer } from "@/components/lesson-viewer";
import type { Lesson } from "@/lib/lessons";
import { visualForLesson, generateLessonVisual, getCachedVisual } from "@/lib/lesson-visuals";
import { Loader2, Sparkles, ArrowLeft } from "lucide-react";
import { Button } from "@/components/ui/button";

/**
 * AiLesson — the single lesson pipeline. Every lesson in the platform,
 * catalog entry or free-text search, is generated by the model for its
 * own topic and rendered through the shared interactive engine.
 */
export function AiLesson({ topic, lessonId }: { topic: string; lessonId: string }) {
  const { data, isLoading, error, refetch, isFetching } = useQuery({
    queryKey: ["gen-lesson", topic.toLowerCase()],
    queryFn: async () => {
      const result = await generateLesson({ data: { topic } });
      if (!result.ok) throw new Error(result.message);
      return result.lesson;
    },
    staleTime: Infinity,
    gcTime: Infinity,
    retry: 0,
  });

  // Topic-specific artwork: one hero plus one image per step, cached per topic.
  const [hero, setHero] = useState<string | undefined>(() => getCachedVisual(topic));
  const [stepArt, setStepArt] = useState<Record<string, string>>({});
  const requested = useRef<Set<string>>(new Set());

  // Hero art only — step art is generated lazily when the learner arrives.
  useEffect(() => {
    if (!data || hero) return;
    let active = true;
    (async () => {
      const url = await generateLessonVisual(topic, data.category);
      if (active && url) setHero(url);
    })();
    return () => {
      active = false;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [data, topic]);

  /** Generate (or reuse) artwork for one step, on demand. */
  const ensureStepArt = useCallback(
    async (stepId: string) => {
      if (!data || stepArt[stepId] || requested.current.has(stepId)) return;
      const step = data.steps.find((s) => s.id === stepId);
      if (!step) return;
      const variant = `${step.title} — ${step.intro}`;
      const cached = getCachedVisual(topic, variant);
      if (cached) {
        setStepArt((p) => ({ ...p, [stepId]: cached }));
        return;
      }
      requested.current.add(stepId);
      const url = await generateLessonVisual(topic, data.category, variant);
      if (url) setStepArt((p) => ({ ...p, [stepId]: url }));
    },
    [data, stepArt, topic],
  );

  if (isLoading || (isFetching && !data)) {
    return (
      <div className="flex min-h-screen flex-col items-center justify-center gap-5 p-6 text-center">
        <div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-gradient-to-br from-ember to-primary shadow-glow">
          <Sparkles className="h-7 w-7 text-primary-foreground" />
        </div>
        <div>
          <p className="font-mono text-[10px] uppercase tracking-[0.28em] text-ember">
            Sensei is designing your lesson
          </p>
          <p className="mt-2 font-serif text-2xl">"{topic}"</p>
        </div>
        <p className="max-w-md text-sm text-muted-foreground">
          Structuring learning objectives, tools, safety notes, and hands-on hotspots into an interactive lesson.
        </p>
        <Loader2 className="h-5 w-5 animate-spin text-ember" />
      </div>
    );
  }

  if (error || !data) {
    return (
      <div className="flex min-h-screen flex-col items-center justify-center gap-4 p-6 text-center">
        <p className="font-mono text-xs uppercase tracking-widest text-ember">Generation failed</p>
        <p className="max-w-md text-sm text-muted-foreground">
          {(error as Error)?.message ?? "Something went wrong. Try again in a moment."}
        </p>
        <div className="flex gap-2">
          <Button variant="outline" asChild>
            <Link to="/library">
              <ArrowLeft className="mr-1 h-4 w-4" /> Library
            </Link>
          </Button>
          <Button onClick={() => refetch()} className="shadow-glow">
            Try again
          </Button>
        </div>
      </div>
    );
  }

  const cover =
    hero ?? visualForLesson({ category: data.category, title: data.title, summary: data.summary });

  const lesson: Lesson = {
    id: lessonId,
    title: data.title,
    category: data.category,
    instructor: data.instructor,
    level: data.level,
    totalMinutes: data.totalMinutes,
    cover,
    summary: data.summary,
    environment: data.environment,
    steps: data.steps.map((s) => {
      const scene = stepArt[s.id] ?? cover;
      return {
        id: s.id,
        title: s.title,
        scene,
        intro: s.intro,
        duration: s.duration,
        hotspots: s.hotspots.map((h) => ({
          id: h.id,
          label: h.label,
          x: h.x,
          y: h.y,
          action: h.action,
          why: h.why,
          tips: h.tips,
          warning: h.warning,
          mistake: h.mistake,
          demo: {
            kind: "action-demo" as const,
            scene,
            x: h.x,
            y: h.y,
            duration: 4.5,
            topic,
            category: data.category,
            label: h.label,
            action: h.action,
          },
        })),
      };
    }),
  };

  return (
    <div>
      <div className="border-b border-ember/30 bg-ember/10 px-4 py-2 text-center text-xs">
        <span className="font-mono uppercase tracking-widest text-ember">AI-Generated</span>
        <span className="ml-2 text-muted-foreground">
          Designed live by Sensei · Objectives: {data.objectives.slice(0, 3).join(" · ")}
        </span>
      </div>
      <LessonViewer lesson={lesson} onStepEnter={(stepId) => void ensureStepArt(stepId)} />
    </div>
  );
}
